import type { Metadata } from 'next';
import { Manrope, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ViewportIndicator } from '@/components/viewport-indicator';
import { ThemeToggle } from '@/components/theme-toggle';
import { ThemeProvider } from 'next-themes';

const manrope = Manrope({
	variable: '--font-manrope',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700']
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${manrope.className} ${geistMono.variable} antialiased`}>
				<ThemeProvider defaultTheme="system" attribute="class">
					{children}
					<ThemeToggle />
					<ViewportIndicator />
				</ThemeProvider>
			</body>
		</html>
	);
}
