import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";
import { HydrationOverlay } from "@builder.io/react-hydration-overlay";

import { ThemeToggle } from "@/components/theme-toggle";
import { ViewportIndicator } from "@/components/viewport-indicator";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HydrationOverlay>
          <ThemeProvider defaultTheme="system" attribute="class">
            <TooltipProvider>
              {children}
              <ThemeToggle />
              <ViewportIndicator />
            </TooltipProvider>
          </ThemeProvider>
        </HydrationOverlay>
      </body>
    </html>
  );
}
